### PR TITLE
Announcements

### PR DESCRIPTION
**Pull request by AyoubC00**
Added pagination functionality for unpinned (regular) announcements.

### CODE REVIEW

**Review by Brahimdriouach — APPROVED** [review]
i didn't test yet but i know you well

**Review by Brahimdriouach — APPROVED** [review]
do we need to manage announcement in frontend ?

**Comment by AyoubC00** [comment]
Depends on how the data is being returned from the backend

**Comment by AyoubC00** [comment]
> do we need to manage announcement in frontend ?

I don't know if I understood you statement correctly but if you refer to the way I inserted the data into the store, that's just a temporary measure. The data will be fetched from the backend.

**Pull request merged**
